# -*- coding: utf-8 -*-
"""praktek_Day02pyGMTCrossMap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjcBqwC46vYa6i-hRitCewAvckfLTqI7

# **Tutorial 3** - Peta Geofisika / Seismologi

Tutorial ini adalah lanjutan dari pembuatan Peta Overlay dengan PyGMT, yaitu membuat peta penampang silang (_cross section_) :

## 0️⃣ Preparasi
"""

## Tahap Installasi di colab
!sudo apt-get update
!sudo apt-get install -y build-essential cmake gdal-bin libgdal-dev \
    ghostscript libfftw3-dev libcurl4-gnutls-dev libnetcdf-dev netcdf-bin \
    libpcre2-dev libcurl4-openssl-dev libglib2.0-dev liblapack-dev \
    libblas-dev libopenblas-dev

!sudo apt-get install -y gmt gdal-bin libgdal-dev libnetcdf-dev netcdf-bin ghostscript

!ls /usr/lib/x86_64-linux-gnu/libgmt*

!sudo ln -s /usr/lib/x86_64-linux-gnu/libgmt.so.6 /usr/lib/x86_64-linux-gnu/libgmt.so

!pip install pygmt==0.13.0 numpy pandas cartopy elevation netcdf4 scipy

"""Impor paket yang diperlukan. Selain [`PyGMT`](https://www.pygmt.org/v0.13.0), kami juga menggunakan [`GeoPandas`](https://geopandas.org/) dan [`pandas`](https://pandas.pydata.org/)."""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import pygmt
import geopandas as gpd

volcanoes = pd.read_csv("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/data/Indo_Volcanoes.csv", delimiter=';')
stationBMKG = pd.read_csv("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/data/Station_BMKG_Now.csv", delimiter=';')
ISC_EHB = pd.read_csv("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/data/ISC-EHB_1964_2022.csv", delimiter=';')
# slab2 = pd.read_csv("./input/hal_slab2_clp_02.23.18.csv",delim_whitespace=True,header=None)
slab2 = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/hal_slab2_dep_contours_filtered.dat"
faults = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/2016-NMolucca.gmt"
trench = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/trench.gmt"
plates = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/PB2002_plates.txt"
TOPOBATH = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/GRD/Topo_Bath_NMolucca.nc"
TOPOBATH_dat = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/GRD/Topo_Bath_NMolucca.txt"

cpt=r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/topobathy.cpt"
cpt_slab = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/slab_contour.cpt"
cpt_eq = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/seis.cpt"
output_fig = r"Day01_Study_Area.png"

region = [123.75, 129, -1.55, 4.5]
exp_text = 0.175

"""## 1️⃣ Siapkan data bergrid: [`pygmt.xyz2grd`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.xyz2grd.html)

Terkadang, data spasial (regional atau global) disediakan dalam bentuk data tabel (.txt atau .csv) yang berisi kolom x, y, dan z.
"""

import pygmt

input_grd = "/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/GRD/Topo_Bath_NMolucca.nc"
output_ascii = "/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/GRD/Topo_Bath_NMolucca.xyz"

pygmt.grd2xyz(grid=input_grd,outfile=output_ascii )
print("✔️ Convert selesai → ASCII XYZ")

import numpy as np

with open("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/GRD/Topo_Bath_NMolucca.xyz") as f:
     txt = f.read().replace(",", ".")  # ganti koma → titik

# # Load dari string
from io import StringIO
data = np.loadtxt(StringIO(txt))

print(data)

"""Kita harus mengonversi `numpy.ndarray` menjadi grid yang siap digunakan dengan GMT melalui [`pygmt.xyz2grd`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.xyz2grd.html). Oleh karena itu, Anda perlu menyediakan:

1. `data` atau `x`, `y`, `z`: Berkas teks input. Penting: Jika Anda menggunakan `data`, urutan kolom harus longitude, latitude, dan data. Jika tidak, Anda harus menggunakan `x`, `y`, dan `z` untuk mendefinisikan dataset secara terpisah.
2. `region`: Menentukan wilayah geografis grid dalam bentuk `[lon_min, lon_max, lat_min, lat_max]`.
3. `spacing`: Jarak grid untuk grid output. Dalam kasus kami, jarak grid dataset asli adalah `1m` (1 menit busur), kami tidak melakukan interpolasi ke resolusi yang lebih tinggi, karena hal itu dapat menyebabkan distorsi data.
"""

grid = pygmt.xyz2grd(data=data, spacing="15s", region=region)

"""Kita dapat memperoleh informasi tentang grid menggunakan [`pygmt.grdinfo`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.grdinfo.html):"""

print(pygmt.grdinfo(grid))

"""## 2️⃣ Buat peta kontur: [`pygmt.Figure.grdcontour`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.Figure.grdcontour.html)
Untuk menggambar grid atau gambar sebagai garis kontur, Anda dapat menggunakan [`pygmt.Figure.grdcontour`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.Figure.grdcontour.html). Anda perlu mendefinisikan:

1. `grid`: Akses dataset jarak jauh atau berikan dataset Anda sebagai [`xarray.DataArray`](https://docs.xarray.dev/en/v2024.09.0/generated/xarray.DataArray.html).
2. `level`: Tentukan interval kontur yang akan dihasilkan; misalnya, nilai 1000 berarti menggambar garis kontur setiap 1000 m.
3. `annotation`: Berikan anotasi pada tingkat kontur.
4. `limit`: Gambarkan kontur di bawah batas bawah atau di atas batas atas, misalnya [-4000, 0] berarti menggambar garis kontur di bawah permukaan laut dan di atas -4000 m.

Sebelum menggambar grid sebagai garis kontur, kita menggambar grid dengan kode warna menggunakan [`pygmt.Figure.grdimage`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.Figure.grdimage.html). Melalui parameter `shading`, kita dapat menerapkan pencahayaan pada grid atau gambar, yang dapat membantu menciptakan peta yang menarik secara visual. Dengan melewatkan argumen **+a**, kita menggunakan azimuth -45 derajat. Jalankan sel kode berikutnya dua kali, pertama tanpa pencahayaan dan kedua dengan pencahayaan, untuk melihat perbedaannya. Untuk pencahayaan yang lebih kompleks, silakan merujuk ke [`pygmt.grdgradient`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.grdgradient.html), yang telah diperkenalkan dalam [Day 01](./Day01_pyGMT_Map.ipynb).
"""

def calculate_rectangle(start, end, width):
    x1, y1 = start
    x2, y2 = end

    # Convert width from km to degrees (approximation)
    width_deg = width / 111.32  # 1 degree ~ 111.32 km at the equator

    # Calculate direction vector of the line
    dx, dy = x2 - x1, y2 - y1
    length = np.sqrt(dx**2 + dy**2)

    # Normalize to unit vector
    dx /= length
    dy /= length

    # Perpendicular vector (rotate 90 degrees)
    px, py = -dy, dx

    # Offset points
    p1 = (x1 + px * width_deg, y1 + py * width_deg)
    p2 = (x1 - px * width_deg, y1 - py * width_deg)
    p3 = (x2 - px * width_deg, y2 - py * width_deg)
    p4 = (x2 + px * width_deg, y2 + py * width_deg)

    return [p1, p2, p3, p4, p1]  # Close the rectangle

fig = pygmt.Figure()
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

grid=r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/GRD/Topo_Bath_NMolucca.nc"

fig.grdimage(projection="M12c",region=region, grid=grid, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt", transparency=25, shading="+a")
fig.basemap(projection="M12c", region=region, frame="a10f5")

fig.colorbar(cmap=cpt, frame=["xa2000f1000+lElevation", "y+lm"])

fig.grdcontour(
    grid=grid,
    annotation="1000+fgray20",
    levels=1000,
    limit=[-6000, 0],
    pen="0.5p,white@20",
)
fig.show()

"""## 3️⃣ Buat grafik profil: [`pygmt.project`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.project.html) and [`pygmt.grdtrack`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.grdtrack.html)

### **3.1 Pilih profil**

Pertama, kita memilih profil atau garis survei di dalam area studi kita dan menggambarkannya di atas peta geografis kita.
"""

fig = pygmt.Figure()
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

grid=r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/GRD/Topo_Bath_NMolucca.nc"

fig.grdimage(projection="M12c",region=region, grid=grid, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt", transparency=25, shading="+a")
fig.basemap(projection="M12c", region=region, frame="a10f5")

fig.colorbar(cmap=cpt, frame=["xa2000f1000+lElevation", "y+lm"])

pointA = [124.9, 1.7]  # Point A (lon, lat)
pointB = [128.5, 0.7]    # Point B

fig.grdcontour(
    grid=grid,
    annotation="1000+fgray20",
    levels=1000,
    limit=[-6000, 0],
    pen="0.5p,white@20",
)
fig.plot(x=[pointA[0],pointB[0]], y=[pointA[1],pointB[1]], pen='0.75p,blue')
fig.text(
    x=[pointA[0],pointB[0]],
    y=[pointA[1],pointB[1]],
    text=["A", "B"],
    fill='white',
    pen="0.25p,black,solid",
    clearance='0.1/0.1+tO',
#     offset="0c/0.2c",
    justify="MC",
    no_clip=True,  # Do not clip text that fall outside the plot bounds
    font="8p,Helvetica-Bold",  # Use a font size of 10 points
)
fig.savefig("Day02_Study_Area_AB.png", dpi=300)
fig.show()

"""### **3.2 [`pygmt.project`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.project.html)**

[`pygmt.project`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.project.html) dirancang untuk mengambil sampel titik sepanjang lingkaran besar, garis lurus, atau pada jarak yang ditentukan. Dalam kasus kami, kami akan membuat profil titik ke titik. Oleh karena itu, Anda perlu mendefinisikan:

1. `center` dan `endpoint`: Tentukan koordinat awal dan akhir profil.
2. `generate`: Interval jarak setiap titik, misalnya `10` berarti titik-titik dihasilkan setiap 10 derajat sepanjang profil.
3. `unit` (opsional): Secara default, `unit=False`, jarak titik-titik sepanjang profil diukur dalam derajat. Ketika `unit=True` digunakan, hal ini menentukan bahwa jarak dihasilkan dalam kilometer.
"""

import numpy as np
import pandas as pd
import pygmt

# ----------------------------
# 1. Load Volcano Catalog
# ----------------------------
Volcano_Database = pd.read_csv("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/data/Indo_Volcanoes.csv", delimiter=';')
cols = ["Name", "Longitude", "Latitude", "Elevation (m)"]
Volcano = Volcano_Database[cols].copy()
Volcano["Elevation (m)"] = pd.to_numeric(Volcano["Elevation (m)"], errors="coerce")
# jadikan semua titik z = -3.5 km untuk plotting di penampang
Volcano = Volcano.rename(columns={
    "Longitude": "lon",
    "Latitude": "lat",
    "Elevation (m)": "Elevation_km"
})
Volcano["Elevation_km"] = 5.5  # override semua elevasi
Volcano = Volcano.rename(columns={"Elevation_km": "z"})
Volcano = Volcano[["lon", "lat", "z", "Name"]]




# ----------------------------
# 2. Define single cross-section line
# ----------------------------
pointA = [124.9, 1.7]  # Point A (lon, lat)
pointB = [128.5, 0.7]    # Point B

width_cross = 25  # km left-right width
width_str = f"-{width_cross}/{width_cross}"

SLAB_HAL = "/content/hal_slab2_dep_02.23.18.grd"

# ----------------------------
# 3. Sample points along the line
# ----------------------------
print(f"Processing cross-section A–B ...")

proj_AB = pygmt.project(
    center=pointA,
    endpoint=pointB,
    generate="1k",   # sampling tiap 1 km
    unit=True,
    width=width_str,
)

# ----------------------------
# 4. Project volcanoes ke lintasan A–B
# ----------------------------
try:
    vc_AB = pygmt.project(
        data=Volcano,
        center=pointA,
        endpoint=pointB,
        convention="pz",
        width=width_str,
        unit=True
    )

    if vc_AB is None or vc_AB.empty:
        print("⚠️ No volcano along this cross-section.")
    else:
        print(f"✔️ Volcano points found: {len(vc_AB)}")

    vc_filename = "/content/slice_slab_AB.dat"
    vc_AB.to_csv(vc_filename, sep="\t", index=False)
    print(f"✔️ Saved projected volcano data: {vc_filename}")

except Exception as e:
    print(f"❌ Error volcano projection: {e}")



print("\n>>> DONE: Cross-section A–B complete!")

"""**Catatan**: Format keluaran adalah `pandas.DataFrame`, dan **r** dan **s** bersama-sama memberikan koordinat geografis (bujur, lintang) dari setiap titik sepanjang lintasan, sementara **p** memberikan jarak kumulatif sepanjang profil hingga setiap titik.

### **3.3 [`pygmt.grdtrack`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.grdtrack.html)**

Kemudian, kita menggunakan [`pygmt.grdtrack`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.grdtrack.html) untuk mengambil nilai topografi (atau data grid lainnya) sepanjang profil yang Anda buat menggunakan [`pygmt.project`] (https://www.pygmt.org/v0.13.0/api/generated/pygmt.project.html). Ini memungkinkan Anda untuk mengambil data dari file grid sepanjang jalur yang ditentukan. Oleh karena itu, Anda perlu menyediakan:

1. `grid`: Tentukan file grid (misalnya, grid topografi) dari mana data akan diambil.
2. `points`: Berikan koordinat titik-titik profil.
3. `newcolname`: Nama kolom baru yang berisi nilai-nilai yang diambil.
"""

# Ekstrak ketinggian di titik-titik yang dihasilkan dari grid yang diunduh
# dan tambahkan sebagai kolom baru “elevation” ke pandas.DataFrame
# ----------------------------
# 5. Grdtrack -> ambil nilai slab
# ----------------------------
slab_AB = pygmt.grdtrack(
    grid="/content/hal_slab2_dep_02.23.18.grd",
    points=proj_AB,
    newcolname="slab",
    interpolation="b"
)
slab_clean = slab_AB.dropna()
slab_filename = "/content/slice_slab_AB.dat"
slab_clean.to_csv(slab_filename, sep="\t", index=False)
print(f"✔️ Saved slab file: {slab_filename}")

# Buat lintasan cross-section
track_df = pygmt.project(
    center=pointA,
    endpoint=pointB,
    generate="0.001",
    unit=True,
)

# --- FIX: Handle spaces in grid path for grdtrack ---
# The error "File /content/drive/MyDrive/Visualisasi was not found"
# indicates that the space in the 'grid' path is causing issues with GMT's underlying command.
# To fix this, we will copy the grid file to a temporary path without spaces.
import os
import shutil

original_grid_path = grid
temp_grid_path = "/tmp/Topo_Bath_NMolucca.nc" # A temporary path without spaces

# Check if the original grid file exists before copying
if os.path.exists(original_grid_path):
    shutil.copy(original_grid_path, temp_grid_path)
    print(f"✔️ Copied '{original_grid_path}' to '{temp_grid_path}' for grdtrack.")
else:
    print(f"❌ Error: Original grid file not found at '{original_grid_path}'.")
    # For now, let's raise an error if the file isn't found
    raise FileNotFoundError(f"Original grid file not found at '{original_grid_path}'.")

# Ambil elevasi dari grid bathymetri menggunakan temporary path
track_df = pygmt.grdtrack(
    grid=temp_grid_path, # Use the temporary path
    points=track_df,
    newcolname="elevation",
)
# --- END FIX ---

"""**Catatan**: Kolom baru ini adalah **elevation** untuk menunjukkan variasi ketinggian sepanjang profil.

Kita dapat mengamati nilai minimum dan maksimum dari data ketinggian ini.
"""

print(min(track_df["elevation"]), max(track_df["elevation"]))
track_df

"""### **3.4 Buat grafik Cartesian yang menampilkan ketinggian sepanjang profil**

Sekarang, kita ingin memvisualisasikan ketinggian sepanjang profil dalam grafik Cartesian. Oleh karena itu, kita menambahkan panel lain ke gambar kita. Gunakan [`Figure.shift_origin`](https://www.pygmt.org/v0.13.0/api/generated/pygmt. Figure.shift_origin.html) untuk memindahkan titik asal plot ke bagian atas peta geografis dan membuat peta dasar baru melalui [`Figure.basemap`](https://www.pygmt.org/v0.13.0/api/generated/pygmt.Figure.basemap.html).
"""

from geopy.distance import geodesic
import pygmt

# ---------------------------
# Asumsi: region, grid, cpt, track_df sudah ada
# ---------------------------
# contoh safety-check (opsional)
if "p" not in track_df.columns or "elevation" not in track_df.columns:
    raise ValueError("track_df harus berisi kolom 'p' dan 'elevation'")

# titik A dan B (lon, lat)
pointA = [124.9, 1.7]  # Point A (lon, lat)
pointB = [128.5, 0.7]    # Point B

# geodesic expects (lat, lon)
lat1, lon1 = pointA[1], pointA[0]
lat2, lon2 = pointB[1], pointB[0]
distance_km = round(geodesic((lat1, lon1), (lat2, lon2)).kilometers, 2)

fig = pygmt.Figure()

# Konfigurasi global PyGMT
pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A0")
pygmt.config(FORMAT_GEO_MAP="ddd.xxxF")
pygmt.config(FONT_ANNOT="12p")
pygmt.config(FONT_LABEL="12p")
pygmt.config(FONT_TITLE="12p")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="10p,Helvetica")
pygmt.config(MAP_TITLE_OFFSET="2p")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

# --- Peta geografis utama (peta raster/gridded) ---
fig.grdimage(grid=grid, projection="M13c", region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
             transparency=25, shading="+a")

# frame & graticule
fig.basemap(projection="M13c", region=region, frame="a2f1")

# Kontur (perbaikan annotation & levels)
# annotation: tulis interval + font (contoh "1000+f8p" artinya label setiap 1000 dengan font 8p)
fig.grdcontour(
    grid=grid,
    annotation="1000+fgray20",
    levels=1000,
    limit=[-6000, 1000],
    pen="0.5p,white@20",
)
fig.plot(x=Volcano["lon"], y=Volcano["lat"], fill="red1",  style="kvolcano/7p", pen="0.25", transparency="10")

# garis profil antara A dan B
fig.plot(x=[pointA[0], pointB[0]], y=[pointA[1], pointB[1]], pen='0.75p,blue')

# teks penanda A & B di peta (letakkan sedikit offset supaya tidak menimpa titik)
fig.text(x=pointA[0], y=pointA[1], text="A",
         justify="CM",  # center middle
         font="8p,Helvetica-Bold,black",
         offset="0.1c/0.1c",clearance='0.1/0.1+tO',
         no_clip=True)

fig.text(x=pointB[0], y=pointB[1], text="B",
         justify="CM",
         font="8p,Helvetica-Bold,black",
         offset="0.1c/0.1c",clearance='0.1/0.1+tO',
         no_clip=True)

fig.text(
    x=[pointA[0],pointB[0]],
    y=[pointA[1],pointB[1]],
    text=["A", "B"],
    fill='white',
    pen="0.25p,black,solid",
    clearance='0.1/0.1+tO',
#     offset="0c/0.2c",
    justify="MC",
    no_clip=True,  # Do not clip text that fall outside the plot bounds
    font="8p,Helvetica-Bold",  # Use a font size of 10 points
)

# colorbar
fig.colorbar(cmap=cpt, frame=["xa2000f1000+lElevation", "y+lm"])

# optional: tulis jarak A-B di pojok peta
fig.text(x=region[0] + 0.15, y=region[3] - 0.15,
         text=f"Distance A–B: {distance_km} km",
         font="9p,Helvetica,black",
         justify="LB",
         no_clip=True)

# --- Geser origin untuk plot penampang (di atas peta) ---
# Gunakan yshift yang wajar; contoh "h+1.75c" agar penampang berada di atas peta
fig.shift_origin(yshift="h+1.75c")

# setting axis untuk penampang
max_p = float(track_df["p"].max())
max_elev = float(track_df["elevation"].max())

fig.basemap(
    region=[0, max_p, -5000, max_elev + 500],
    projection="X13c/3c",
    frame=["WSrt", "xa25f12.5+lDistance / km", "ya1000+lElevation / m"],
)

# teks penanda A & B pada penampang
fig.text(x=0, y=max_elev + 200, text="A", offset="0c/0.3c",
         no_clip=True, font="10p,Helvetica-Bold,white", fill="red")
fig.text(x=max_p, y=max_elev + 200, text="B", offset="0c/0.3c",
         no_clip=True, font="10p,Helvetica-Bold,white", fill="red")

# tampilkan
fig.savefig("Day02_Cross_Section_AB_noTrack.png", dpi=300)
fig.show()

# Buat polygon area air (dari 0 ke max_p, dan baseline -5000)
water_poly_x = [0, max_p, max_p, 0]
water_poly_y = [0, 0, -5000, -5000]
fig.plot(x=water_poly_x, y=water_poly_y, fill="lightblue", close=True)

# Buat polygon elevasi (menggabungkan profil + baseline -5000)
# Pastikan track_df terurut menurut 'p'
track_df_sorted = track_df.sort_values(by="p")
poly_x = track_df_sorted["p"].tolist()
poly_y = track_df_sorted["elevation"].tolist()
# tambahkan titik penutup ke baseline
poly_x = poly_x + [track_df_sorted["p"].iloc[-1], track_df_sorted["p"].iloc[0]]
poly_y = poly_y + [-5000, -5000]
fig.plot(x=poly_x, y=poly_y, fill="lightgray", pen="1p,red", close=True)

# Garis elevasi (outline) — jika mau garis terpisah
fig.plot(x=track_df_sorted["p"], y=track_df_sorted["elevation"], pen="1p,red")

# Menambahkan simbol gunung berapi di penampang
vc_file = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/slice/slice_vc_AB.dat"
data_vc = pd.read_csv(vc_file, delimiter="\t", header=None, names=["Distance (km)", "Elev (km)", "Name"])

fig.plot(x=data_vc["Distance (km)"], y=data_vc["Elev (km)"],no_clip=True, style="kvolcano/9p", pen="0.25", transparency="30",fill="red3")

fig.savefig("Day02_Cross_Section_AB.png", dpi=300)
fig.show()

"""#### 🗺️ Plot Peta & Penampang A–B (PyGMT)

Dokumentasi ini menjelaskan seluruh langkah pembuatan **peta topografi** dan **penampang elevasi A–B**, termasuk penjelasan **fungsi PyGMT** yang digunakan.

---

> 🔧 1. Import Library
```python
from geopy.distance import geodesic
import pygmt
```
**Penjelasan fungsi:**
- `geodesic()` → menghitung jarak permukaan bumi antar koordinat.
- `pygmt` → library wrapper Python untuk GMT (Generic Mapping Tools).

---

> 📦 2. Validasi Data Profil
```python
if "p" not in track_df.columns or "elevation" not in track_df.columns:
    raise ValueError("track_df harus berisi kolom 'p' dan 'elevation'")
```
**Fungsi:** memastikan data profil memiliki dua kolom wajib:
- `p` → jarak kumulatif (km)
- `elevation` → elevasi (meter)

---

> 📍 3. Titik A–B dan Jarak Geodesik
```python
pointA = [124.9, 1.7]
pointB = [128.5, 0.7]

lat1, lon1 = pointA[1], pointA[0]
lat2, lon2 = pointB[1], pointB[0]
distance_km = round(geodesic((lat1, lon1), (lat2, lon2)).kilometers, 2)
```

---

> 🖼️ 4. Membuat Figure PyGMT
```python
fig = pygmt.Figure()
```
**Fungsi:**  
`pygmt.Figure()` → tempat menampung semua elemen peta/plot.

---

> ⚙️ 5. Konfigurasi Global PyGMT
```python
pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A0")
pygmt.config(FORMAT_GEO_MAP="ddd.xxxF")
...
```

**Penjelasan beberapa konfigurasi:**
- `MAP_FRAME_TYPE="plain"` → frame tanpa border tebal.
- `PS_MEDIA="A0"` → ukuran halaman besar A0.
- `FORMAT_GEO_MAP` → format label derajat.
- `MAP_GRID_PEN_PRIMARY` → style garis grid.
- `FONT_*` → mengatur font global GMT.

---

> 🌍 6. Menampilkan Raster DEM
```python
fig.grdimage(grid=grid, projection="M13c", region=region, cmap=cpt,
             transparency=25, shading="+a")
```
**Fungsi PyGMT:**
- `grdimage()` → menampilkan grid (DEM/topografi) sebagai peta raster.
- `projection="M13c"` → peta Mercator lebar 13 cm.
- `region` → batas lon/lat.
- `cmap` → color palette.
- `shading="+a"` → hillshade otomatis.
- `transparency=25` → grid sedikit transparan.

---

> 🧭 7. Frame & Grid Koordinat
```python
fig.basemap(projection="M13c", region=region, frame="a2f1")
```
**Fungsi PyGMT:**
- `basemap()` → mengatur frame, grid, axis, tick.
- `frame="a2f1"` → anotasi tiap 2°, minor tick tiap 1°.

---

> ⛰️ 8. Kontur Elevasi
```python
fig.grdcontour(
    grid=grid,
    annotation="1000+fgray20",
    levels=1000,
    limit=[-6000, 0],
    pen="0.5p,white@20",
)
```
**Fungsi PyGMT:**
- `grdcontour()` → membuat kontur dari grid.
- `levels=1000` → kontur tiap 1000 m.
- `annotation="1000+fgray20"` → label kontur warna abu.
- `limit=[-6000,0]` → hanya tampil untuk elevasi negatif → laut.

---

> ➖ 9. Garis Profil A–B
```python
fig.plot(x=[pointA[0], pointB[0]], y=[pointA[1], pointB[1]], pen="0.75p,blue")
```
**Fungsi PyGMT:**
- `plot()` → menggambar garis, simbol, atau polygon.
- `pen="0.75p,blue"` → garis biru tipis.

---

> 🔤 10. Label A–B di Peta
```python
fig.text(...)

fig.text(...)

fig.text(...)
```
**Fungsi PyGMT:**
- `text()` → menempelkan teks di peta.
- `offset` → menggeser label sedikit.
- `fill="white"` → background putih.
- `pen="0.25p"` → outline teks.

---

> 🎨 11. Colorbar
```python
fig.colorbar(cmap=cpt, frame=["xa2000f1000+lElevation", "y+lm"])
```
**Fungsi PyGMT:**
- `colorbar()` → membuat colorbar.
- `xa2000f1000` → major tick 2000 m, minor 1000 m.

---

> 📏 12. Info Jarak A–B
```python
fig.text(x=region[0] + 0.15, y=region[3] - 0.15,
         text=f"Distance A–B: {distance_km} km",
         font="9p,Helvetica,black",
         justify="LB",
         no_clip=True)
```

---

#### 📊 Bagian 2 — Penampang A–B

---

> ↕️ 13. Geser Origin Plot
```python
fig.shift_origin(yshift="h+1.75c")
```
**Fungsi PyGMT:**
- `shift_origin()` → memindahkan sistem koordinat ke posisi baru,  
  digunakan untuk menaruh profil di atas peta.

---

> 📐 14. Basemap Penampang
```python
fig.basemap(
    region=[0, max_p, -5000, max_elev + 500],
    projection="X13c/3c",
    frame=["WSrt", "xa25f12.5+lDistance / km", "ya1000+lElevation / m"],
)
```
**Fungsi PyGMT:**
- `projection="X13c/3c"` → grafik Cartesian 13 cm × 3 cm.
- `xa25f12.5` → major tick 25 km, minor tick 12.5 km.
- `ya1000` → major tick elevasi 1000 m.

---

> 🅰️🅱️ 15. Label Profil A–B
```python
fig.text(...)
fig.text(...)
```
Label diberi outline agar tetap terlihat.

---

> 🌊 16. Area Laut (Water Polygon)
```python
water_poly_x = [0, max_p, max_p, 0]
water_poly_y = [0, 0, -5000, -5000]
fig.plot(x=water_poly_x, y=water_poly_y, fill="lightblue", close=True)
```
**Fungsi PyGMT:**
- `plot(fill="lightblue")` → shading area laut.
- `close=True` → menutup polygon.

---

> 🏔️ 17. Area Daratan (Land Polygon)
```python
track_df_sorted = track_df.sort_values(by="p")
poly_x = track_df_sorted["p"].tolist()
poly_y = track_df_sorted["elevation"].tolist()

poly_x = poly_x + [track_df_sorted["p"].iloc[-1], track_df_sorted["p"].iloc[0]]
poly_y = poly_y + [-5000, -5000]

fig.plot(x=poly_x, y=poly_y, fill="lightgray", pen="1p,red", close=True)
```
**Fungsi PyGMT:**
- Mengisi area daratan di atas permukaan laut.
- Outline merah untuk elevasi permukaan tanah.

---

> 📉 18. Garis Elevasi Utama
```python
fig.plot(x=track_df_sorted["p"], y=track_df_sorted["elevation"], pen="1p,red")
```

---

> 👁️ 19. Menampilkan Figure
```python
fig.show()
```
**Fungsi:** menampilkan output visual.

---

✅ Selesai!

## 4️⃣ Fitur-fitur tambahan
Akhirnya, Anda dapat menambahkan fitur tambahan di atas peta geografis. Silakan tambahkan ide-ide Anda sendiri di sini! Berikut beberapa ide yang dapat Anda coba:
- **Menampilkan seismisitas** : Lihat sub-bagian 4.1
- **Sorot gempa bumi tertentu sebagai bola pantai** : Lihat sub-bagian 4.2
- **Menandai zona slab subduksi**: Gunakan garis depan (line front) untuk menunjukkan patahan; gunakan contoh Galeri [Line fronts](https://www.pygmt.org/v0.13.0/gallery/lines/linefronts.html) sebagai panduan- **Sertakan pergerakan lempeng**: Gunakan panah untuk menunjukkan arah dan kecepatan; gunakan contoh Galeri [Vektor Kartesius, lingkaran, dan geografis](https://www.pygmt.org/v0.13.0/gallery/lines/vector_styles.html) untuk panduan

Kami menyediakan data kegempaan antara tanggal 1964-01-01 dan 2022-12-31 dalam bentuk file CSV di repositori atau tutorial ini. Data ini diperoleh melalui [Katalog ISC-EHB](https://www.isc.ac.uk/isc-ehb/search/catalogue/)
"""

ISC_EHB = pd.read_csv("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/data/ISC-EHB_1964_2022.csv", delimiter=';')

# --- Rename kolom agar seragam ---
ISC_EHB = ISC_EHB.rename(columns={
    "glon": "lon",
    "glat": "lat",
    "depth": "z",
    "mb": "mb",        # pastikan nama tetap
    "mw": "mw",
    "ms": "ms"
})

# Jika mb adalah string kosong, jadikan NaN
if "mb" in ISC_EHB.columns:
    ISC_EHB["mb"] = ISC_EHB["mb"].replace(["", " ", "-", "-9.9"], np.nan)
else:
    ISC_EHB["mb"] = np.nan

# fallback: jika mb kosong, pakai Mw, lalu Ms
ISC_EHB["M"] = (
    ISC_EHB["mb"]
    .fillna(ISC_EHB.get("mw"))
    .fillna(ISC_EHB.get("ms"))
)
# Isi magnitude kosong dengan 0
ISC_EHB["M"] = ISC_EHB["M"].fillna(0)

EQ = ISC_EHB[["lon", "lat", "z", "M"]].copy()


pointA = [124.9, 1.7]
pointB = [128.5, 0.7]


width_cross=25
width_str = f"-{width_cross}/{width_cross}"

print(f"▶ Projecting for cross-section...")
projected_df = pygmt.project(
    data=EQ,
    unit=True,                  # hasil dalam km
    center=pointA,
    endpoint=pointB,
    convention="pz",            # profil tegak lurus ke garis lintasan
    width=[-width_cross, width_cross],
)
output_filename = "/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/slice/slice_EQ.dat"
projected_df.to_csv(output_filename, sep='\t', index=False)

print(f"✅ Saved projected data to {output_filename}")

from geopy.distance import geodesic
import pygmt

# ---------------------------
# Asumsi: region, grid, cpt, track_df sudah ada
# ---------------------------
region_map_width = round((region[1] - region[0]) * 111.1,3)
# contoh safety-check (opsional)
if "p" not in track_df.columns or "elevation" not in track_df.columns:
    raise ValueError("track_df harus berisi kolom 'p' dan 'elevation'")

# titik A dan B (lon, lat)
pointA = [124.9, 1.7]
pointB = [128.5, 0.7]

# geodesic expects (lat, lon)
lat1, lon1 = pointA[1], pointA[0]
lat2, lon2 = pointB[1], pointB[0]
distance_km = round(geodesic((lat1, lon1), (lat2, lon2)).kilometers, 2)
depth_max = 300
fig = pygmt.Figure()

# Konfigurasi global PyGMT
pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A0")
pygmt.config(FORMAT_GEO_MAP="ddd.xxxF")
pygmt.config(FONT_ANNOT="12p")
pygmt.config(FONT_LABEL="12p")
pygmt.config(FONT_TITLE="12p")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="10p,Helvetica")
pygmt.config(MAP_TITLE_OFFSET="2p")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

# --- Peta geografis utama (peta raster/gridded) ---
fig.grdimage(grid=grid, projection="M13c", region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
             transparency=25, shading="+a")

# frame & graticule
fig.basemap(projection="M13c", region=region, frame="a2f1")
fig.coast(
    region=region,
    projection="M13c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
)

# Kontur (perbaikan annotation & levels)
# annotation: tulis interval + font (contoh "1000+f8p" artinya label setiap 1000 dengan font 8p)
fig.grdcontour(
    grid=grid,
    annotation="1000+fgray20",
    levels=1000,
    limit=[-6000, 1000],
    pen="0.5p,white@20",
)
fig.plot(x=Volcano["lon"], y=Volcano["lat"], fill="red1",  style="kvolcano/7p", pen="0.25", transparency="10")

# garis profil antara A dan B
fig.plot(x=[pointA[0], pointB[0]], y=[pointA[1], pointB[1]], pen='0.75p,blue')

# teks penanda A & B di peta (letakkan sedikit offset supaya tidak menimpa titik)
fig.text(x=pointA[0], y=pointA[1], text="A",
         justify="CM",  # center middle
         font="8p,Helvetica-Bold,black",
         offset="0.1c/0.1c",clearance='0.1/0.1+tO',
         no_clip=True)

fig.text(x=pointB[0], y=pointB[1], text="B",
         justify="CM",
         font="8p,Helvetica-Bold,black",
         offset="0.1c/0.1c",clearance='0.1/0.1+tO',
         no_clip=True)

fig.text(
    x=[pointA[0],pointB[0]],
    y=[pointA[1],pointB[1]],
    text=["A", "B"],
    fill='white',
    pen="0.25p,black,solid",
    clearance='0.1/0.1+tO',
#     offset="0c/0.2c",
    justify="MC",
    no_clip=True,  # Do not clip text that fall outside the plot bounds
    font="8p,Helvetica-Bold",  # Use a font size of 10 points
)

# colorbar
fig.colorbar(cmap=cpt, frame=["xa2000f1000+lElevation", "y+lm"])
fig.plot(region=region, projection="M13c",
    x=ISC_EHB['lon'].values,
    y=ISC_EHB['lat'].values,
    fill=ISC_EHB['z'].values,
    style='c',
    cmap=cpt_eq,
    size=(1.75**ISC_EHB['M'])/175,       # from dataframe
    pen='0.0001p,black@50',
    )
# optional: tulis jarak A-B di pojok peta
fig.text(x=region[0] + 0.15, y=region[3] - 0.15,
         text=f"Distance A–B: {distance_km} km",
         font="9p,Helvetica,black",
         justify="LB",
         no_clip=True)

# --- Geser origin untuk plot penampang (di atas peta) ---
# Gunakan yshift yang wajar; contoh "h+1.75c" agar penampang berada di atas peta
fig.shift_origin(yshift="h+1.75c")

# setting axis untuk penampang
max_p = float(track_df["p"].max())
max_elev = float(track_df["elevation"].max())

fig.basemap(
    region=[0, max_p, -5000, max_elev + 500],
    projection="X13c/3c",
    frame=["WSrt", "xa25f12.5+lDistance / km", "ya1000+lElevation / m"],
)
# Menambahkan simbol gunung berapi di penampang
vc_file = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/slice/slice_vc_AB.dat"
data_vc = pd.read_csv(vc_file, delimiter="\t", header=None, names=["Distance (km)", "Elev (km)", "Name"])

# teks penanda A & B pada penampang
fig.text(x=0, y=max_elev + 200, text="A", offset="0c/0.3c",
         no_clip=True, font="10p,Helvetica-Bold,white", fill="red")
fig.text(x=max_p, y=max_elev + 200, text="B", offset="0c/0.3c",
         no_clip=True, font="10p,Helvetica-Bold,white", fill="red")
# Buat polygon area air (dari 0 ke max_p, dan baseline -5000)
water_poly_x = [0, max_p, max_p, 0]
water_poly_y = [0, 0, -5000, -5000]
fig.plot(x=water_poly_x, y=water_poly_y, fill="lightblue", close=True)

# Buat polygon elevasi (menggabungkan profil + baseline -5000)
# Pastikan track_df terurut menurut 'p'
track_df_sorted = track_df.sort_values(by="p")
poly_x = track_df_sorted["p"].tolist()
poly_y = track_df_sorted["elevation"].tolist()
# tambahkan titik penutup ke baseline
poly_x = poly_x + [track_df_sorted["p"].iloc[-1], track_df_sorted["p"].iloc[0]]
poly_y = poly_y + [-5000, -5000]
fig.plot(x=poly_x, y=poly_y, fill="lightgray", pen="1p,red", close=True)

# Garis elevasi (outline) — jika mau garis terpisah
fig.plot(x=track_df_sorted["p"], y=track_df_sorted["elevation"], pen="1p,red")
fig.plot(x=data_vc["Distance (km)"], y=data_vc["Elev (km)"]+10,no_clip=True, style="kvolcano/9p", pen="0.25", transparency="30",fill="red3")


fig.shift_origin( yshift="h-15.5c", xshift="w+2c")  # geser ke bawah untuk penampang 2
save_cross_sect = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/slice/slice_EQ.dat" # change this
data_cross = np.loadtxt(save_cross_sect)
y = data_cross[:, 1]        # take all data from column depth
data_cross = pd.DataFrame(data_cross, columns = ["Distance (km)", "Depth (km)", "Magnitude"])
slab_file = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/slice/slice_slab_AB.dat"
data_slab = pd.read_csv(slab_file, delimiter="\t")

# Penampang 1: Panjang disesuaikan dengan jarak di km
fig.basemap(
    projection=f"X{13}c/-{13*(distance_km/region_map_width)}",  # Proporsi tinggi sesuai panjang peta utama
    region=[0, distance_km, -2, depth_max+1],
    frame=["x+lDistance (km)", "yafg+lDepth (km)", "WSe+gwhitesmoke@50"]
)
fig.plot(x=data_cross["Distance (km)"], y=data_cross["Depth (km)"], fill=data_cross["Depth (km)"].astype(int),
         cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/seis.cpt",
         projection=f"X{13}c/-{13*(distance_km/region_map_width)}",
        #  style='c0.075c',
        #  pen='0.1p,black'
         size=(1.75**data_cross['Magnitude'])/175,
         style="c",
         pen="0.25p,black@30"
         )
fig.plot(x=data_slab['p'], y=data_slab['slab']*-1, pen="0.75p,blue,solid")


# Garis elevasi (outline) — jika mau garis terpisah
fig.plot(x=track_df_sorted["p"], y=track_df_sorted["elevation"]/1000,no_clip=True, pen="1p,red")
# Menambahkan simbol gunung berapi di penampang
vc_file = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/slice/slice_vc_AB.dat"
data_vc = pd.read_csv(vc_file, delimiter="\t", header=None, names=["Distance (km)", "Elev (km)", "Name"])
fig.plot(x=data_vc["Distance (km)"], y=data_vc["Elev (km)"]*-1,no_clip=True, style="kvolcano/9p", pen="0.25", transparency="30",fill="red3")

fig.text(
    x=[0, distance_km],
    y=[-3, -3],
    text=["A", "B'"],
    fill='white',
    pen="0.25p,black,solid",
    clearance='0.1/0.1+tO',
    no_clip=True,  # Do not clip text that fall outside the plot bounds
    font="9p,Helvetica-Bold",  # Use a font size of 10 points
)

# tampilkan
fig.savefig("Day02_Cross_Section_EQ_AB.png", dpi=300)
fig.show()