# -*- coding: utf-8 -*-
"""praktek)Day01pyGMTMap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FULh_lnPrTqmlKJqrW0ln83olTLLw-YY

# **Pre Tutorial** - Membuat PyGMT *Environment* (di dalam *environment* `conda` baru)

Kita mengasumsikan bahwa `conda` sudah terpasang, kemungkinan melalui program [Anaconda](https://www.anaconda.com/).
Kita akan menginstal *environment* baru dengan semua *python package* yang Anda butuhkan untuk tutorial ini.
Perhatikan bahwa Anda mungkin sudah memiliki instalasi gmt lain yang berpotensi bertabrakan dengan ini.
Jika telah memiliki environment conda yang memiliki pyGMT silahkan abaikan tahapan ini.

## Tahapan Instalasi
    # tested using python.v3.11, and pygmt.v0.17.0
    conda create --name pygmt --channel conda-forge ipython ipykernel jupyter numpy pandas gmt pygmt cartopy elevation netcdf4 scipy
   
*Anda mungkin ingin menghapus instalasi `gmt` sebelumnya di luar lingkungan python, karena mungkin bertentangan.*

## Masuk ke environment
> command-line operations
```
cd {Folder_Tutorial}
conda activate pygmt
```

## Buka Jupyter Notebooks / Visual Studio Code
> Apabila menggunakan Visual Studio Code tambahkan folder tutorial kedalam Visual Studio Code
```
File > Add Folder to Workspace > {Folder_Tutorial}
```
> Apabila menggunakan jupyter Notebooks pastikan anda berada di folder yang sama dengan *file* '.ipynb'
```
jupyter notebook
```
> Buka file 01_pyGMT_First_Figure.ipynb, lalu jalan script dibawah menggunakan kernel pygmt.
"""

## Tahap Installasi di colab
!sudo apt-get update
!sudo apt-get install -y build-essential cmake gdal-bin libgdal-dev \
    ghostscript libfftw3-dev libcurl4-gnutls-dev libnetcdf-dev netcdf-bin \
    libpcre2-dev libcurl4-openssl-dev libglib2.0-dev liblapack-dev \
    libblas-dev libopenblas-dev

!sudo apt-get install -y gmt gdal-bin libgdal-dev libnetcdf-dev netcdf-bin ghostscript

!ls /usr/lib/x86_64-linux-gnu/libgmt*

!pip install pygmt==0.13.0

!sudo ln -s /usr/lib/x86_64-linux-gnu/libgmt.so.6 /usr/lib/x86_64-linux-gnu/libgmt.so

import pygmt
pygmt.show_versions()

fig=pygmt.Figure()
pygmt.config(PS_MEDIA="A4")
fig.coast(region='g',frame=True, shorelines=1)

fig.show()
fig.savefig("test_map.png", dpi=300)

"""# **Tutorial 1** - Gambar pertama 🚀 dan Subplot / tata letak

Tutorial ini akan membahas konsep dasar dalam membuat gambar dengan PyGMT:

- Menggambar garis pantai (*coastlines*)
- Menggambar bingkai peta
- Memilih proyeksi
- Mengunduh dataset jarak jauh
- Menampilkan relief Bumi
- Membuat skala warna (*colorbar*)
- Subplot dalam gambar

## 0️⃣ Impor modul PyGMT

Hal pertama yang perlu dilakukan adalah memuat PyGMT (`import`) agar kita dapat mengakses fungsionalitasnya.

PyGMT memiliki struktur paket yang sederhana, artinya Anda dapat mengakses semua komponen di dalamnya dengan satu perintah `import`.
"""

import pygmt

"""## 1️⃣ Mulai gambar pertama Anda -- [`pygmt.Figure`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.html)
Setiap gambar harus dimulai dengan pembuatan pygmt.Figure()
"""

fig = pygmt.Figure()

"""Kita memiliki kanvas kosong di variabel `fig` sekarang, Kita akan melapisi elemen dan menampilkannya di `fig` yang sama.

### 1.1 Menggambar garis pantai -- [`pygmt.Figure.coast`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.coast.html)
Sebelum membuat plot, Anda perlu mendefinisikannya
1. `region`: Mengontrol cakupan geografis atau Cartesian dari gambar tersebut. Wilayah ditentukan sebagai daftar `[xmin, xmax, ymin, ymax]`. Pintasan lain, `region="g"`, yang menentukan domain **global**.
2. `projection`: Mengontrol proyeksi peta. GMT (dan PyGMT) mendukung 31 proyeksi peta yang berbeda, mulai dari sumbu Cartesian dasar hingga [perspektif vertikal sembarang](https://docs.generic-mapping-tools.org/6.5/gallery/ex26.html).

> Menentukan ukuran gambar Anda `10c`, ukuran tersebut akan mempengaruhi seberapa besar ukuran font dan ukuran penanda berikut Anda
>> **satuan panjang** `c`: sentimeter (default)

> Proyeksi selengkapnya silakan klik https://www.pygmt.org/v0.17.0/projections/index.html
"""

pygmt.config(PS_MEDIA="A4")

region = [94, 145, -16, 15]

fig.coast(region=region, projection="M10c", shorelines=True)

# To see the figure looks like
fig.savefig("Day01_Indonesia_Map.png", dpi=300)
fig.show()

"""**_lihat juga_**

Di Jupyter, `show` akan menyematkan gambar PNG langsung ke Jupyter Notebook. Tapi itu juga bisa membuka PDF di penampil eksternal, yang mungkin Anda inginkan jika Anda menggunakan skrip Python biasa. Lihat dokumentasi untuk [`pygmt.Figure.show`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.show.html#pygmt.Figure.show) untuk informasi selengkapnya.

### 1.2 Pewarnaan dan penambahan elemen peta (bingkai dan tanda skala)  
1. Label sumbu `WSne`: Jika huruf besar (W, S, N, E) diberikan, sumbu akan digambar dengan tanda skala dan anotasi. Versi huruf kecil (w, s, n, e) hanya menggambar sumbu dengan tanda skala. Untuk hanya menggambar sumbu, berikan (l, b, t, r).

2. anotasi `a`: label tanda skala  
3. bingkai `f`: tanda skala  
4. grid `g`: garis grid pada gambar.  

<img src="./_static/tut01_frame.jpg" alt="frame" />  

> Detail lebih lanjut tentang bingkai https://www.pygmt.org/v0.17.0/tutorials/basics/frames.html

> Lebih banyak warna https://docs.generic-mapping-tools.org/6.6/gmtcolors.html#list-of-colors
"""

fig.coast(water="lightblue", land="grey", frame=["WSne", "a10f5g5"])
fig.show()

"""### 1.3 Menyimpan gambar ke berkas -- [`pygmt.Figure.savefig`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.savefig)
Untuk menyimpan gambar ke berkas, Anda dapat menggunakan metode [`pygmt.Figure.savefig`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.savefig), dan memberikan nama berkas dan ekstensi yang diinginkan ke parameter `fname`.
"""

fig.savefig(fname="my_first_figure.png")

"""### 1.4 Pendekatan Penumpukan dalam GMT/PyGMT  
1. Dalam GMT/PyGMT, pembuatan grafik dilakukan dengan menumpuk elemen-elemen baru, artinya setiap elemen baru ditumpuk di atas lapisan sebelumnya.  
Oleh karena itu, jika Anda menggambar garis hitam pada lapisan sebelumnya dan kemudian menambahkan lapisan baru (seperti pengisian warna), lapisan-lapisan baru ini mungkin akan menutupi garis hitam asli, sehingga tidak terlihat.
2. Dalam sebuah **gambar yang sama**, setelah Anda mendefinisikan wilayah/proyeksi sebelumnya, Anda tidak perlu mendefinisikannya lagi.

## 2️⃣ Mengunduh dataset global -- [`pygmt.datasets`](https://www.pygmt.org/v0.17.0/api/index.html#datasets)

Sebelum mengakses dataset jarak jauh dari PyGMT, Anda perlu mendefinisikan
1. `region`: Wilayah yang diinginkan, formatnya adalah [xmin, xmax, ymin, ymax]
2. `resolution`: Resolusi grid. Suffiks **d** (derajat busur), **m** (menit busur), dan **s** (detik busur).
"""

grid = pygmt.datasets.load_earth_relief(resolution="15m", region=region)

# Anda juga dapat mengakses dan memotong grid
# dan dengan cara ini dapat menyimpan grid (outgrid) sebagai file di folder Anda.
# https://www.generic-mapping-tools.org/remote-datasets/

pygmt.grdcut(
   grid="@earth_relief_01m", region=region, outgrid="Indonesia.grd"
)

"""Cara untuk memverifikasi informasi grid Anda [`pygmt.grdinfo`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.grdinfo.html)"""

print(pygmt.grdinfo(grid=grid))

"""## 3️⃣ Visualisasi grid -- [`pygmt.Figure.grdimage`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.grdimage.html)
Proyeksikan dan plot grid atau gambar

Sekarang, kita mulai dengan kanvas baru. Jadi, Anda perlu mengatur wilayah/proyeksi lagi!

Sebelum memproses gambar, Anda perlu mendefinisikan
1. `grid`: Menentukan file grid (misalnya, grid topografi) dari mana data akan diambil.
"""

fig = pygmt.Figure()
pygmt.config(PS_MEDIA="A4")

fig.grdimage(grid=grid, region=region, projection="M13c")

fig.coast(shorelines="0.25p,black", frame=["WSne", "a5f2.5"])

fig.show()
fig.savefig("Day01_Indonesia_Grid_Map.png", dpi=300)

"""### 3.1 Menyesuaikan palet warna -- [`pygmt.makecpt`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.makecpt.html)  
Membuat tabel palet warna GMT (CPT).

Anda perlu mendefinisikan:
1. `cmap`: Memilih palet warna untuk memvisualisasikan grid/dataset Anda.
> Sumber daya palet warna tambahan https://docs.generic-mapping-tools.org/6.5/_images/GMT_App_M_1a.png

2. `series`: Menentukan rentang CPT dengan memberikan nilai z terendah dan tertinggi. Contoh: [0, 500] (tanpa interval) atau [0, 500, 10] (menentukan interval)
"""

from google.colab import drive
drive.mount('/content/drive')

pygmt.makecpt(
    cmap="geo",
    series=[-8000, 7000, 500],
    continuous=True,
    # The file name with extension .cpt to store the generated CPT file
    output="eleva.cpt",
)

"""Sekarang, plot ulang gambar dengan peta warna baru dan ...
### 3.2 Menambahkan [`pygmt.Figure.colorbar`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.colorbar.html)
Menampilkan skala abu-abu atau warna pada peta.

Anda perlu mendefinisikan,
1. `cmap`: Nama file CPT
2. `frame`: Pengaturan batas skala warna, label, dan atribut sumbu

    > * **+l** untuk judul skala warna

3. `position`: Menentukan titik referensi pada peta untuk skala warna

   > Empat sistem koordinat:
   >  * **g** untuk koordinat peta (pengguna)
   >  * **j** atau **J** untuk menetapkan titik referensi melalui kode justifikasi dua karakter
   >  * **x** untuk koordinat plot: x/y (posisi spesifik)
   >  * **n** untuk koordinat dinormalisasi (0-1)

   > Lainnya
   >  * **+w** untuk panjang dan lebar skala warna. Contoh: +w10c/0.5c
   >  * **+h** untuk bilah warna horizontal, jika ingin menggambar bilah warna vertikal, gunakan **+v**
   >  * **+m** untuk posisi judul bilah warna

<img src="_static/tut01_colorbar_position.jpg" alt="position" />
"""

fig = pygmt.Figure()
pygmt.config(PS_MEDIA="A0")

fig.grdimage(grid=grid, region=region, projection="M13c", cmap="eleva.cpt")

fig.coast(shorelines="0.25p,black", frame=["WSne", "a5f2.5"])

fig.colorbar(
    cmap="eleva.cpt",
    frame="a2000f500+lElevation (m)",
    position="JBC+w10c/0.4c+mc+h",
)

fig.show()
fig.savefig("Day01_Indonesia_Grid_Map_v2.png", dpi=300)

"""## 4️⃣ Membuat gambar dengan beberapa panel di kanvas -- [`pygmt.Figure.subplot`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.subplot.html#pygmt.Figure.subplot) dan [`pygmt.Figure.set_panel`](https://www.pygmt.org/v0.17.0/api/generated/pygmt.Figure.set_panel.html#pygmt.Figure.set_panel)


Anda perlu mendefinisikan tata letak gambar dengan figure.subplot:
1. `nrows`: Jumlah baris vertikal
2. `ncols`: Jumlah kolom horizontal
3. `figsize` atau `subsize`: Dimensi keseluruhan gambar, misalnya [lebar, tinggi]
4. `margins`: Mengatur jarak antar subplot. Contoh: ``["1c", "2c", "3c", "4c"]``

Kedua, mengatur setiap plot dengan figure.set_panel:
1. `panel`: Mengatur panel subplot saat ini untuk digambar. Misalnya, **indeks** atau [**baris**, **kolom**]

<img src="_static/tut01_subplot.jpg" alt="subplot" />
"""

fig = pygmt.Figure()
pygmt.config(PS_MEDIA="A0")
grid_crust_age = pygmt.datasets.load_earth_age(
    resolution="01m", region=[94, 145, -16, 15]
)

with fig.subplot(nrows=1, ncols=2, figsize=["18c", "12c"],margins=["0.5c", "0.5c"]):

    with fig.set_panel(panel=0):

        fig.grdimage(
            grid=grid,
            region=region,
            # "?" means that map width automatically determined from the subplot width.
            projection="M?",
            cmap="eleva.cpt",
        )
        fig.coast(shorelines="0.25p,black", frame=["WSne", "a5f2.5"])
        fig.colorbar(
            cmap="eleva.cpt",
            position="JBC+w8c/0.3c+mc+h",
            frame="a2000f500+lElevation (m)",
        )

    with fig.set_panel(panel=1):

        pygmt.makecpt(cmap="@earth_age.cpt", series=[0, 340])
        fig.grdimage(
            grid=grid_crust_age,
            region=[94, 145, -16, 11],
            # changing projection method
            projection="L118/-2.5/4/-9/?",
            frame=["a5f2.5", "SEnw"],
            cmap=True,
        )
        fig.coast(shorelines="0.25p,black", frame=["WSne", "a5f2.5"])

        fig.colorbar(
            position="JBC+w6c/0.3c+mc+h", frame="a40f20+lSeafloor crustal age (Ma)"
        )

fig.show()
fig.savefig("Day01_Indonesia_Grid_Subset_Map.png", dpi=300)

"""## 5️⃣ Jenis proyeksi dasar<img src="_static/tut01_projection.jpg" alt="posisi" />
Secara default, PyGMT akan menggunakan proyeksi silinder ekuidistan jika wilayah tersebut tampaknya menggunakan koordinat lintang dan bujur geografis.

1. Proyeksi Mercator -- memetakan Bumi ke silinder, menjaga sudut, sehingga berguna untuk tujuan navigasi.
   
   * Kasus Penggunaan: Ideal untuk peta dunia di mana arah perlu dipertahankan, seperti navigasi maritim. Proyeksi ini mendistorsi ukuran, terutama di dekat kutub.
   * Perintah GMT: **M[lon]/[lat]**, menentukan bujur dan lintang pusat.

1. Proyeksi Konik -- memproyeksikan Bumi ke dalam kerucut.   

   * Penggunaan: Untuk peta regional, terutama di negara-negara berlatitude sedang, di mana distorsi bentuk dan area diminimalkan dalam rentang latitude tertentu.

   * Perintah GMT: **L[lon0]/[lat0]/[lat1]/[lat2]**, di mana lon0 dan lat0 mendefinisikan **pusat proyeksi** dan lat1/lat2 mendefinisikan **_standard parallels_**.

2. Proyeksi Azimuthal -- memproyeksikan Bumi ke atas bidang datar, menjaga arah dari titik pusat.

   * Penggunaan: Cocok untuk pemetaan wilayah kutub atau area mana pun di mana arah dari titik pusat sangat penting.
   * Perintah GMT: **E[lon]/[lat]**, dengan lon dan lat mendefinisikan titik pusat.

# **Tutorial 2** - Peta Geofisika / Seismologi

Tutorial ini akan membahas pembuatan Peta Overlay dengan PyGMT untuk banyak objek diantaranya:

- Garis pantai (*coastlines*)
- Topografi dan/atau Batimetri
- Sesar
- Gunung Api
- *Trench*
- *Subduction Slab*
- Teks
- Katalog Gempa
- Skala warna (*colorbar*)
- Legenda
- Peta Inset

## Import modul
"""

!pip install geopandas

import pandas as pd
import pygmt
import geopandas as gpd

volcanoes = pd.read_csv("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/data/Indo_Volcanoes.csv", delimiter=';')
stationBMKG = pd.read_csv("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/data/Station_BMKG_Now.csv", delimiter=';')
ISC_EHB = pd.read_csv("/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/data/ISC-EHB_1964_2022.csv", delimiter=';')
# slab2 = pd.read_csv("./input/hal_slab2_clp_02.23.18.csv",delim_whitespace=True,header=None)
slab2 = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/hal_slab2_dep_contours_filtered.dat"
faults = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/2016-NMolucca.gmt"
trench = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/trench.gmt"
plates = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/PB2002_plates.txt"
TOPOBATH = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/GRD/Topo_Bath_NMolucca.nc"
cpt=r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/topobathy.cpt"
cpt_slab = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/slab_contour.cpt"
cpt_eq = r"/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/seis.cpt"
output_fig = r"Day01_Study_Area.png"

region = [123.75, 129, -1.55, 4.5]
# sumatra : region=[94, 106, -6.5, 6.5]

exp_text = 0.175

"""### Konfigurasi pengaturan peta 🎯-- [`pygmt.config`](https://www.pygmt.org/dev/api/generated/pygmt.config.html)

```python
pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")
```

- 🖼 **MAP_FRAME_TYPE = "plain"**  
  Bingkai peta sederhana.  
  👉 Pilihan lain: `fancy`, `graph`, `inside`, `outside`

- 📄 **PS_MEDIA = "A4"**  
  Ukuran media output A4.  
  👉 Bisa: `letter`, `legal`, `A3`, `auto`

- 🧭 **FORMAT_GEO_MAP = "ddd.xxF"**  
  Format derajat desimal (110.25°).  
  👉 Alternatif: `dddF`, `ddd:mmF`, `ddd:mm:ssF`

- 🔠 **FONT_ANNOT = "10p"**  
  Ukuran font anotasi.  
  👉 Eksperimen: `8p`, `9p`, `"10p,Helvetica"`

- 🏷 **FONT_LABEL = "10p"**  
  Font label sumbu.  
  👉 Bisa: `"12p,Bold"`, `"9p,Times-Italic"`

- 📰 **FONT_TITLE = "10p,Palatino-Bold"**  
  Font judul peta.  
  👉 Alternatif: `Helvetica-Bold`, `Times-Bold`

- 📐 **MAP_GRID_PEN_PRIMARY = "0.2p,gray,--"**  
  Garis grid utama putus-putus.  
  👉 Warna: `black`, `red`; Tipe garis: `-`, `--`, `:`  

- 🔤 **FONT_ANNOT_PRIMARY = "8p,Helvetica"**  
  Font untuk angka grid utama.  
  👉 Coba: `7p`, `9p`, `Times-Roman`

- ↔️ **MAP_ANNOT_OFFSET_PRIMARY = "2.5p"**  
  Jarak anotasi dari frame.  
  👉 Pilihan: `1p`, `3p`, `5p`

- 🧭 **MAP_ANNOT_OBLIQUE = "lon_horizontal,lat_parallel,tick_normal"**  
  Orientasi teks koordinat.  
  👉 Bisa: `lon_vertical`, `lat_horizontal`, `tick_parallel`

Kumpulan *Font*: (https://www.pygmt.org/v0.17.0/techref/fonts.html)

Kumpulan Warna: (https://docs.generic-mapping-tools.org/6.6/gmtcolors.html)

### **01. Garis Pantai (*Coastlines*)**
"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="fancy")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)

fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")

fig.show()
fig.savefig("Day01_Study_Area.png", dpi=300)

"""### **02. Topografi dan/atau Batimetri**"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)
fig.show()
fig.savefig("Day01_Study_Area_TopoBath.png", dpi=300)

"""### **03. Sesar**

Sesar aktif bersumber dari data sesar PuSGeN 2017
"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)

fig.plot(data=faults, pen="1.0,red3", label="Fault")

fig.show()
fig.savefig("Day01_Study_Area_TopoBath_Faults.png", dpi=300)

"""### **04. Trench**"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)

fig.plot(data=faults, pen="1.0,red3", label="Fault")
fig.plot(data=trench, pen="0.50", style="f0.15c/0.05c+l+t", fill="black", label="Trench")
fig.show()
fig.savefig("Day01_Study_Area_TopoBath_Faults_Trench.png", dpi=300)

"""### **05. Subduction Slab**

SLAB2 by Hayes dkk. (2020)
"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)

fig.plot(data=faults, pen="1.0,red3", label="Fault")
fig.plot(data=trench, pen="0.50", style="f0.15c/0.05c+l+t", fill="black", label="Trench")
fig.plot(data=slab2, projection="M12c", pen='0.5', cmap=cpt_slab)

# 🔥 Tambahkan COLORBAR
fig.colorbar(
    cmap=cpt_slab,
    frame=["x+lSlab depth (km)"],
    position="JMR+w8c/0.4c+o1c/0"
)

fig.show()
fig.savefig("Day01_Study_Area_TopoBath_Faults_Trench_Slab.png", dpi=300)

"""### **06. Volcano**

[List_of_volcanoes_in_Indonesia](https://en.wikipedia.org/wiki/List_of_volcanoes_in_Indonesia)
"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)

fig.plot(data=faults, pen="1.0,red3", label="Fault")
fig.plot(data=trench, pen="0.50", style="f0.15c/0.05c+l+t", fill="black", label="Trench")
fig.plot(data=slab2, projection="M12c", pen='0.5', cmap=cpt_slab)
fig.plot(x=volcanoes["Longitude"], y=volcanoes["Latitude"], fill="red1",  style="kvolcano/7p", pen="0.25", transparency="10")
fig.plot(x=[0], y=[0], fill="red1",  style="t7p", pen="0.25", transparency="10", label="Volcano")

fig.show()
fig.savefig("Day01_Study_Area_TopoBath_Faults_Trench_Slab_Volcanoes.png", dpi=300)

"""### **07. Label Teks**"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)

fig.plot(data=faults, pen="1.0,red3", label="Fault")
fig.plot(data=trench, pen="0.50", style="f0.15c/0.05c+l+t", fill="black", label="Trench")
fig.plot(x=volcanoes["Longitude"], y=volcanoes["Latitude"], fill="red1",  style="kvolcano/7p", pen="0.25", transparency="10")
fig.plot(x=[0], y=[0], fill="red1",  style="t7p", pen="0.25", transparency="10", label="Volcano")

fig.plot(data=slab2, projection="M12c", pen='0.35', cmap=cpt_slab)

fig.text(text=["Sangihe Thrust"], x=[124.945], y=[0.6], angle="60", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Halmahera Thrust"], x=[126.8], y=[-0.15], angle="80", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Philippine Trench"], x=[128.7], y=[3.3], angle="305", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Molucca Sea Collision Zone"], x=[126.], y=[1], angle="70", font="9p,Palatino-Roman,Red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Molucca Sea"], x=[126.], y=[-1], angle="0", font="10p,Palatino-Italic,blue", justify="CM")
fig.text(text=["Sorong F.-South Halmahera"], x=[128.], y=[-1.175], angle="-15", font="8p,Palatino-Bold,red", justify="CM")
fig.text(text=["North Sula F."], x=[125.], y=[-1.275], angle="-15", font="8p,Palatino-Bold,red", justify="CM", )

# ==== Step 7 — Daftar stasiun yang label-nya di bawah ====
volcanoes_kanan = {"Submarine 1922", "Awu", "Ruang", "Karangetang", "Banua Wuhu", "Tongkoko", "Mahawu", "Tondano", "Soputan"}  # <=== ubah sesuai kebutuhanmu

# ==== Step 8 — Tambahkan label nama gunung ====
for _, row in volcanoes.iterrows():
    # Cek apakah stasiun masuk daftar “label di bawah”
    if row['Name'] in volcanoes_kanan:
        offset = f"{exp_text}/0c"  # geser ke kanan
        justify = "LM"
    else:
        offset = f"-{exp_text}/0c"  # geser ke atas kiri (default)
        justify = "RM"

    fig.text(
        text=row['Name'],
        x=row['Longitude'],
        y=row['Latitude'],
        font="7p,Helvetica-Narrow,black@20",
        offset=offset,
        justify=justify,
        fill="white@30",
        clearance="0.05c/0.05c+tO"
        )

fig.show()
fig.savefig("Day01_Study_Area_TopoBath_Faults_Trench_Slab_Volcanoes_Labels.png", dpi=300)

"""### **08. Katalog Gempa**"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)

fig.plot(data=faults, pen="1.0,red3", label="Fault")
fig.plot(data=trench, pen="0.50", style="f0.15c/0.05c+l+t", fill="black", label="Trench")
fig.plot(x=volcanoes["Longitude"], y=volcanoes["Latitude"], fill="red1",  style="kvolcano/7p", pen="0.25", transparency="10")
fig.plot(x=[0], y=[0], fill="red1",  style="t7p", pen="0.25", transparency="10", label="Volcano")

fig.plot(data=slab2, projection="M12c", pen='0.35', cmap=cpt_slab)

fig.text(text=["Sangihe Thrust"], x=[124.945], y=[0.6], angle="60", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Halmahera Thrust"], x=[126.8], y=[-0.15], angle="80", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Philippine Trench"], x=[128.7], y=[3.3], angle="305", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Molucca Sea Collision Zone"], x=[126.], y=[1], angle="70", font="9p,Palatino-Roman,Red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Molucca Sea"], x=[126.], y=[-1], angle="0", font="10p,Palatino-Italic,blue", justify="CM")
fig.text(text=["Sorong F.-South Halmahera"], x=[128.], y=[-1.175], angle="-15", font="8p,Palatino-Bold,red", justify="CM")
fig.text(text=["North Sula F."], x=[125.], y=[-1.275], angle="-15", font="8p,Palatino-Bold,red", justify="CM", )


fig.plot(region=region, projection="M12c",
    x=ISC_EHB['glon'].values,
    y=ISC_EHB['glat'].values,
    fill=ISC_EHB['depth'].values,
    style='c',
    cmap=cpt_eq,
    size=(1.75**ISC_EHB['mb'])/175,       # from dataframe
    pen='0.0001p,black@50',
    )

fig.show()
fig.savefig("Day01_Study_Area_TopoBath_Faults_Trench_Slab_Volcanoes_Labels_Earthquake.png", dpi=300)

"""### **09. Colorbar & Legend**"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.75c/1.75c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/3.5c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "WNse"]
)

fig.plot(data=faults, pen="1.0,red3", label="Fault")
fig.plot(data=trench, pen="0.50", style="f0.15c/0.05c+l+t", fill="black", label="Trench")
fig.plot(x=volcanoes["Longitude"], y=volcanoes["Latitude"], fill="red1",  style="kvolcano/7p", pen="0.25", transparency="10")
fig.plot(x=[0], y=[0], fill="red1",  style="t7p", pen="0.25", transparency="10", label="Volcano")

fig.plot(data=slab2, projection="M12c", pen='0.35', cmap=cpt_slab)

fig.text(text=["Sangihe Thrust"], x=[124.945], y=[0.6], angle="60", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Halmahera Thrust"], x=[126.8], y=[-0.15], angle="80", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Philippine Trench"], x=[128.7], y=[3.3], angle="305", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Molucca Sea Collision Zone"], x=[126.], y=[1], angle="70", font="9p,Palatino-Roman,Red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Molucca Sea"], x=[126.], y=[-1], angle="0", font="10p,Palatino-Italic,blue", justify="CM")
fig.text(text=["Sorong F.-South Halmahera"], x=[128.], y=[-1.175], angle="-15", font="8p,Palatino-Bold,red", justify="CM")
fig.text(text=["North Sula F."], x=[125.], y=[-1.275], angle="-15", font="8p,Palatino-Bold,red", justify="CM", )


fig.plot(region=region, projection="M12c",
    x=ISC_EHB['glon'].values,
    y=ISC_EHB['glat'].values,
    fill=ISC_EHB['depth'].values,
    style='c',
    cmap=cpt_eq,
    size=(1.75**ISC_EHB['mb'])/175,       # from dataframe
    pen='0.0001p,black@50',
    )

fig.colorbar(
    cmap=cpt,
    position="JBC+o0c/0.75c+w8c/0.2c+h+ml",  # kanan tengah horizontal
    frame=[f"xaf+lTopo/Bathy", f"y+lm"]
)
fig.legend(position="jTL+jTL+o0.2c/0.2c", box="+gwhite+p0.5p")

fig.show()
fig.savefig("Day01_Study_Area_Final.png", dpi=300)

"""### **10. Peta Inset**"""

fig = pygmt.Figure()

pygmt.config(MAP_FRAME_TYPE="plain")
pygmt.config(PS_MEDIA="A4")
pygmt.config(FORMAT_GEO_MAP="ddd.xxF")
pygmt.config(FONT_ANNOT="10p")
pygmt.config(FONT_LABEL="10p")
pygmt.config(FONT_TITLE="10p,Palatino-Bold")
pygmt.config(MAP_GRID_PEN_PRIMARY="0.2p,gray,--")
pygmt.config(FONT_ANNOT_PRIMARY="8p,Helvetica")
pygmt.config(MAP_ANNOT_OFFSET_PRIMARY="2.5p")
pygmt.config(MAP_ANNOT_OBLIQUE="lon_horizontal,lat_parallel,tick_normal")

fig.grdimage(grid=TOPOBATH, region=region, cmap="/content/drive/MyDrive/Visualisasi Geoscience Python 3/GeoSoft_Data - Copy/input/afrikakarte.cpt",
            projection="M12c",
            shading="+a245+nt0.8+ne0.65",
            # shading=True,
            # transparency=10
            )
fig.basemap(rose="jTL+w1.25c+o.7c/0.2c+l,,,N",
            region=region,projection="M12c",
            map_scale="jTL+o0.25c/2c+w70+uKm")
fig.coast(
    region=region,
    projection="M12c",
    shorelines="0.25p,black",
    # water="skyblue1",
    lakes="skyblue1",
    resolution="f",
    frame=["a1f0.1", "NEws"]
)

fig.plot(data=faults, pen="1.0,red3", label="Fault")
fig.plot(data=trench, pen="0.50", style="f0.15c/0.05c+l+t", fill="black", label="Trench")
fig.plot(x=volcanoes["Longitude"], y=volcanoes["Latitude"], fill="red1",  style="kvolcano/7p", pen="0.25", transparency="10")
fig.plot(x=[0], y=[0], fill="red1",  style="t7p", pen="0.25", transparency="10", label="Volcano")

fig.plot(data=slab2, projection="M12c", pen='0.35', cmap=cpt_slab)

fig.text(text=["Sangihe Thrust"], x=[124.945], y=[0.6], angle="60", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Halmahera Thrust"], x=[126.8], y=[-0.15], angle="80", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Philippine Trench"], x=[128.7], y=[3.3], angle="305", font="8p,Palatino-Roman,red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Molucca Sea Collision Zone"], x=[126.], y=[1], angle="70", font="9p,Palatino-Roman,Red", justify="CM", fill="white@30", clearance="0.05c/0.05c+tO")
fig.text(text=["Molucca Sea"], x=[126.], y=[-1], angle="0", font="10p,Palatino-Italic,blue", justify="CM")
fig.text(text=["Sorong F.-South Halmahera"], x=[128.], y=[-1.175], angle="-15", font="8p,Palatino-Bold,red", justify="CM")
fig.text(text=["North Sula F."], x=[125.], y=[-1.275], angle="-15", font="8p,Palatino-Bold,red", justify="CM", )

fig.plot(region=region, projection="M12c",
    x=ISC_EHB['glon'].values,
    y=ISC_EHB['glat'].values,
    fill=ISC_EHB['depth'].values,
    style='c',
    cmap=cpt_eq,
    size=(1.75**ISC_EHB['mb'])/175,       # from dataframe
    pen='0.0001p,black@50',
    )

fig.colorbar(
    cmap=cpt,
    position="JBL+o-6c/0.75c+w4c/0.2c+h+ml",  # kanan tengah horizontal
    frame=[f"xaf+lTopo/Bathy", f"y+lm"],
    box="+gwhite@30+p0.8p,black+r2p"
)
fig.colorbar(
    cmap=cpt_eq,
    position="JBR+o-5c/0.75c+w4c/0.2c+h+ml",  # kanan tengah horizontal
    frame=["xa100f50+lhypocentral depth", f"y+lkm"],
    box="+gwhite@30+p0.8p,black+r2p"
)
fig.legend(position="JTL+JTL+o0.25c/-1.65c", box="+gwhite+p0.5p")


region = [region[0], region[1], region[2], region[3]]
lon_min, lon_max, lat_min, lat_max = region
center_str = f"{(lon_min + lon_max) / 2}/{(lat_min + lat_max) / 2}"
projection_ortho = f"G{center_str}/1700/0/5/0/0/0/3c"
pos_study_inset = "jBL+w4.5c+o-1c"

# Inset map of study region
with fig.inset(position=pos_study_inset):
    # >>> use ? <<<

    # Orthographic projection
    # glon0/lat0[/horizon]/scale or Glon0/lat0[/horizon]/width
    #  - lon0 and lat0 projection center
    #  - horizon maximum distance from projection center (in degrees, <= 90, default 90)
    #  - scale and width figure size

    fig.coast(
        region="g",
        projection=projection_ortho,
        resolution="c",
        shorelines="0.01",
        land="azure3",
        water="azure",
        frame="g",
        dcw=["ID+gnavajowhite3+p0.1p"]
    )

    fig.plot(projection=projection_ortho,
        data=[[lon_min, lat_min, lon_max, lat_max]],
        style="r+s",
        pen="0.5p,blue",
        )
    fig.plot(projection=projection_ortho, data=plates, pen='0.5,0', transparency=10)

for m in [3, 4, 5, 6, 7, 8]:
    # mag = 0.1 * 1.4 **m
    mag = (1.75**m)/175
    fig.plot(
        x=[0],
        y=[0],
        fill="gray80@99",
        style='c{}'.format(mag),
        pen='black',label="{}".format(m)
        )
fig.legend(position="JTL+o0.25/-4.25+l1.2",
           box="+c0.12+gwhite+p0.05p"
            )

fig.show()
fig.savefig("Day01_Study_Area_Final_Inset.png", dpi=300)

"""# Tweak

## GRD Modif
"""

import xarray as xr
import pygmt

# === Tentukan region ===
# region = [126.35, 128.5, 0, 2.0]  # batas area cross-section
# region = [124.5, 129, -1.55, 3.75]
# region = [123.75, 129, -2, 4.5]
# === Input grid asli ===
GRD = r"A:\Visa_Data\Demnas_Sulawesi_Utara_Maluku_Utara.nc"
BATH = r"A:\Visa_Data\gebco_2022_n15.0_s-15.0_w90.0_e145.0.nc"
MERGED = r"./GRD/Topo_Bath_NMolucca.nc"

# === 1. Potong grid ke region yang sama ===
GRD_cut = r"./GRD/DEMNAS_CUT.nc"
BATH_cut = r"./GRD/GEBCO_CUT.nc"

print("✂️  Memotong grid ke region terpilih...")
pygmt.grdcut(grid=GRD, region=region, outgrid=GRD_cut)
pygmt.grdcut(grid=BATH, region=region, outgrid=BATH_cut)

# === 2. Baca hasil potongan ===
print("📖 Membaca grid hasil potongan...")
demnas = xr.load_dataarray(GRD_cut)
gebco = xr.load_dataarray(BATH_cut)

# === 3. Samakan dimensi grid laut terhadap darat ===
# GEBCO di-interpolasi agar sesuai grid DEMNAS (tanpa menurunkan resolusi)
gebco_interp = gebco.interp_like(demnas)

# === 4. Gabungkan: daratan pakai DEMNAS, laut pakai GEBCO ===
print("🧩 Menggabungkan DEMNAS + GEBCO ...")
merged = xr.where(demnas > 0, demnas, gebco_interp)

# === 5. Simpan hasil gabungan ===
merged.name = "elevation"
# misal resolusi diperkecil 4x (ubah sesuai kebutuhan)
factor = 2

merged_lowres = merged.coarsen(lat=factor, lon=factor, boundary="trim").mean()

# simpan
merged_lowres.to_netcdf("./GRD/Topo_Bath_NMolucca.nc")

print("🔻 MERGED kualitas diturunkan (downsample).")

"""## Filter Depth Contour Slab2"""

def filter_slab2_contours(
    input_file,
    output_file,
    target_depths
):
    """
    target_depths = list kedalaman yang ingin disimpan (misal: [100, 200, 400]).
    output_file = file *.dat gabungan semua depth yg dipilih.
    """

    target_depths = set(map(float, target_depths))

    out_lines = []
    current_block = []
    current_depth = None

    with open(input_file) as f:
        for line in f:
            stripped = line.strip()

            # Jika header blok, simpan dulu blok yang sebelumnya
            if stripped.startswith(">"):
                # simpan blok sebelumnya jika depth cocok
                if current_block and current_depth in target_depths:
                    out_lines.extend(current_block)

                # mulai blok baru
                current_block = [line]
                current_depth = None
                continue

            # baris data lon lat depth
            parts = stripped.split()
            if len(parts) == 3:
                depth = float(parts[2])
                current_block.append(line)

                # deteksi depth untuk blok ini
                if current_depth is None:
                    current_depth = depth

        # cek blok terakhir
        if current_block and current_depth in target_depths:
            out_lines.extend(current_block)

    # simpan output
    with open(output_file, "w") as f:
        for ln in out_lines:
            f.write(ln)

    print(f"[SAVED] File contour tersaring → {output_file}")



# ============================
# CONTOH PEMAKAIAN
# ============================

input_file = "./input/hal_slab2_dep_contours.dat"

# pilih depth tertentu
depth_yang_diambil = [d for d in range(40, 660, 40)]

output_file = "./input/hal_slab2_dep_contours_filtered.dat"

filter_slab2_contours(input_file, output_file, depth_yang_diambil)